; ERRORS
display_errors = On
log_errors = On

; LOCATION
date.timezone = "America/Montevideo"

; TIMEOUT
max_execution_time = 90

; MAX
upload_max_filesize = 256M
post_max_size = 200M
memory_limit = 256M

; SESSION
; session.save_path = "/home/openimob/public_html/session"
session.gc_maxlifetime = 86400
session.gc_probability = 0

; COMPRESS
; zlib.output_handler = ob_gzhandler
zlib.output_compression = On

; EXTENSIONS
; extension=php_intl.dll